### ISSUE TITLE
/bin/bash: node: command not found

### ISSUE THREAD

**Issue by BeAce** [buildkite/nodejs-example#15]
my yml

![image](https://user-images.githubusercontent.com/13284978/69855167-db942d80-12c5-11ea-81b1-8ab3c863c700.png)

On my macOS `/bin/bash: node: command not found`

![image](https://user-images.githubusercontent.com/13284978/69855152-d20ac580-12c5-11ea-9fa0-408ec3e14401.png)

**Comment by alexgreencode** [comment]
Getting the same. Looks like node.js is not supported by default

**Comment by plaindocs** [comment]
Hi Folks, sorry for the delay. 

If you don't have Node.js on the Agent, the easiest thing to do is to use the [Docker Node.js example](https://github.com/buildkite/nodejs-docker-example).
